---
- name: install jenkins on jenkins master server
  hosts: jenkins-master
  become: true
  tasks:
    - name: import jenkins GPG key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present

    - name: add jenkins repository
      get_url:
        url: http://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: install java (jenkins dependency)
      yum:
        name: java-11-openjdk
        state: present

    - name: install jenkins
      yum:
        name: jenkins
        state: present

    - name: ensure jenkins is enabled and started
      systemd:
        name: jenkins
        enabled: yes
        state: started

    - name: install firewalld
      yum:
        name: firewalld
        state: present

    - name: enable and start firewalld after installation
      systemd:
        name: firewalld
        enabled: yes
        state: started

    - name: open jenkins port in firewalld
      firewalld:
        port: "8080/tcp"
        permanent: yes
        state: enabled
      notify: reload_firewalld

    - name: print jenkins initial admin password
      command: "cat /var/lib/jenkins/secrets/initialAdminPassword"
      register: jenkins_password
      changed_when: false

    - name: show jenkins initial password
      debug:
        msg: "jenkins initial password is {{ jenkins_password.stdout }}"

    - name: inform user jenkins is ready
      debug:
        msg: "jenkins is installed and running on port 8080. Access it via http://<jenkins-server-ip:8080"

  handlers:
    - name: reload_firewalld
      systemd:
        name: firewalld
        state: reloaded
